---
- name: install prometheus -- copy file 1
  copy: src=node_exporter dest={{ prometheus.base_path }}/

- name: install prometheus -- copy file 2
  copy: src=process_exporter dest={{ prometheus.base_path }}/

- name: install prometheus -- copy service 1
  template: src=node_exporter.service.j2  dest=/usr/lib/systemd/system/node_exporter.service

- name: install prometheus -- copy service 2
  template: src=process_exporter.service.j2  dest=/usr/lib/systemd/system/process_exporter.service

- name: install prometheus -- copy sh 1
  template: src=node_exporter_register.sh.j2  dest={{ prometheus.base_path }}/node_exporter/register.sh

- name: install prometheus -- copy sh 2
  template: src=process_exporter_register.sh.j2  dest={{ prometheus.base_path }}/process_exporter/register.sh


- name: install prometheus -- chmod
  shell: "{{ item }} "
  with_items:
    - "chmod u+x {{ prometheus.base_path }}/node_exporter/node_exporter"
    - "chmod u+x {{ prometheus.base_path }}/process_exporter/process_exporter"
    - "chmod u+x {{ prometheus.base_path }}/node_exporter/register.sh"
    - "chmod u+x {{ prometheus.base_path }}/process_exporter/register.sh"

- name: install prometheus -- start service
  shell: "{{ item }} "
  with_items:
    - "systemctl daemon-reload"
    - "systemctl enable node_exporter process_exporter"
    - "systemctl restart node_exporter process_exporter"
    - "{{ prometheus.base_path }}/node_exporter/register.sh"
    - "{{ prometheus.base_path }}/process_exporter/register.sh"